### ISSUE TITLE
Major: Why so many JDKs?

### ISSUE THREAD

**Issue by garethahealy** [makentenza/ocp-pinpoint-apm#3] opened 2017-01-23 14:23 UTC
Why do you provide 6/7/8 ? Also, would suggest moving to OpenJDK. Accepting the license in a docker file has legal problems. i.e.: you are accepting a license on behalf of the user.

https://github.com/makentenza/ocp-pinpoint-apm/blob/master/Dockerfile#L20-L27

**Comment by garethahealy** [comment] 2017-01-23 14:26
Also, is it a good idea to re-distribute the RPM?

https://github.com/makentenza/ocp-pinpoint-apm/blob/master/src/jdk-6u45-linux-amd64.rpm

**Comment by makentenza** [comment] 2017-01-23 14:31
According to developer documentation JDK 6, 7 and 8 are required for building purposes. 

https://github.com/naver/pinpoint#installation

Agree in moving to OpenJDK, but need to check if that works. We could try to.

**Comment by makentenza** [comment] 2017-02-01 09:57
I have tried to move to OpeJDK but getting an error in maven:

ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce (enforce-pinpoint-build-requirements) on project pinpoint: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce (enforce-pinpoint-build-requirements) on project pinpoint: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
	at org.apache.maven.plugins.enforcer.EnforceMojo.execute(EnforceMojo.java:237)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

---

I will try to install OpenJDK 6, 7 and 8 and configure each JAVA_HOME as this seems to be a requirement:

[WARNING] Rule 2: org.apache.maven.plugins.enforcer.RequireEnvironmentVariable failed with message:
Environment variable "JAVA_6_HOME" is required for this build.
[WARNING] Rule 3: org.apache.maven.plugins.enforcer.RequireEnvironmentVariable failed with message:
Environment variable "JAVA_7_HOME" is required for this build.
[WARNING] Rule 4: org.apache.maven.plugins.enforcer.RequireEnvironmentVariable failed with message:
Environment variable "JAVA_8_HOME" is required for this build.

**Comment by makentenza** [comment] 2017-02-01 10:44
I get a failure while compiling pinpoint-thrift module. Can't see further information on the build log about what is causing the error even running maven in Debug mode:

[INFO] pinpoint-thrift .................................... FAILURE [  8.632 s]

**Closed as completed** 2020-07-13 08:48 UTC
